#!/usr/bin/env node

/**
 * Build script to inline JSON files into TypeScript modules
 * This allows the SDK to work in both Node.js and browser environments
 * 
 * Reads ABIs directly from compiled contract artifacts and generates
 * inlined TypeScript modules.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sdkRoot = path.resolve(__dirname, "..");
const contractsRoot = path.resolve(sdkRoot, "../contracts");
const artifactsDir = path.resolve(contractsRoot, "artifacts/src");
const srcDir = path.resolve(sdkRoot, "src");
const generatedDir = path.resolve(srcDir, "generated");

// Contract ABIs to extract from artifacts
const contractAbis = [
  {
    artifactPath: path.resolve(artifactsDir, "AgreementFactory.sol/AgreementFactory.json"),
    output: "AgreementFactoryAbi.ts",
    exportName: "AgreementFactoryABI",
    contractName: "AgreementFactory"
  },
  {
    artifactPath: path.resolve(artifactsDir, "AgreementEngine.sol/AgreementEngine.json"),
    output: "AgreementEngineAbi.ts",
    exportName: "AgreementEngineABI",
    contractName: "AgreementEngine"
  },
];

const deploymentsDir = path.resolve(contractsRoot, "deployments");

function ensureGeneratedDir() {
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
  }
}

function aggregateDeploymentsFromContracts() {
  const registry = { deployments: {} };
  
  if (!fs.existsSync(deploymentsDir)) {
    console.warn(`⚠️  Deployments directory not found: ${path.relative(sdkRoot, deploymentsDir)}`);
    console.warn(`   No deployments will be included. Deploy contracts first.`);
    return registry;
  }

  // Scan all network directories
  const networkDirs = fs.readdirSync(deploymentsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  for (const networkDir of networkDirs) {
    // Ignore local deployments (these are not useful for browser consumers / embedded wallets)
    if (["localhost", "hardhat"].includes(networkDir.toLowerCase())) {
      continue;
    }

    const deploymentFile = path.resolve(deploymentsDir, networkDir, "AgreementsProtocol.json");
    
    if (fs.existsSync(deploymentFile)) {
      try {
        const deploymentInfo = JSON.parse(fs.readFileSync(deploymentFile, "utf-8"));

        // Ignore local chainIds even if placed in another directory by accident
        const chainIdStr = String(deploymentInfo.chainId || "");
        if (["31337", "1337"].includes(chainIdStr)) {
          continue;
        }
        // Ignore explicitly-marked local networks
        const networkName = String(deploymentInfo.network || networkDir || "").toLowerCase();
        if (["localhost", "hardhat"].includes(networkName)) {
          continue;
        }
        
        // Use chainId as the key (as expected by the SDK)
        const chainId = deploymentInfo.chainId;
        if (chainId) {
          // If multiple deployments exist for same chainId, keep the newest one
          const existing = registry.deployments[chainId];
          if (!existing || new Date(deploymentInfo.deployedAt) > new Date(existing.deployedAt)) {
            registry.deployments[chainId] = deploymentInfo;
          }
        }
      } catch (error) {
        console.warn(`⚠️  Failed to read deployment file: ${path.relative(sdkRoot, deploymentFile)}`);
        console.warn(`   Error: ${error.message}`);
      }
    }
  }

  return registry;
}

function extractAbiFromArtifact(artifactPath, contractName) {
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Contract artifact not found: ${artifactPath}\n` +
      `Compile the contracts first (e.g. npm --prefix contracts run compile)`
    );
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  
  // Extract just the ABI array (what the SDK needs)
  if (!artifact.abi || !Array.isArray(artifact.abi)) {
    throw new Error(`Invalid artifact: ${artifactPath} - missing or invalid ABI`);
  }

  return artifact.abi;
}

function inlineAbiFromArtifact(artifactPath, outputPath, exportName, contractName) {
  const abi = extractAbiFromArtifact(artifactPath, contractName);

  // Generate TypeScript file with inlined ABI
  const tsContent = `/**
 * Auto-generated file - DO NOT EDIT
 * This file is generated by scripts/inline-json.mjs
 * Source: ${path.relative(sdkRoot, artifactPath)}
 * 
 * Extracted ABI from compiled contract artifact
 */

export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, tsContent, "utf-8");
  console.log(`✓ Extracted ABI from ${path.relative(sdkRoot, artifactPath)} → ${path.relative(sdkRoot, outputPath)}`);
}

function inlineDeploymentsRegistry(outputPath, exportName) {
  const registry = aggregateDeploymentsFromContracts();
  
  const networkCount = Object.keys(registry.deployments).length;
  const sourceInfo = networkCount > 0 
    ? `Aggregated from ${networkCount} network deployment(s) in ${path.relative(sdkRoot, deploymentsDir)}`
    : `No deployments found in ${path.relative(sdkRoot, deploymentsDir)}`;

  // Generate TypeScript file with inlined deployments registry
  const tsContent = `/**
 * Auto-generated file - DO NOT EDIT
 * This file is generated by scripts/inline-json.mjs
 * ${sourceInfo}
 */

export const ${exportName} = ${JSON.stringify(registry, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, tsContent, "utf-8");
  console.log(`✓ Aggregated deployments from ${path.relative(sdkRoot, deploymentsDir)} → ${path.relative(sdkRoot, outputPath)}`);
  if (networkCount > 0) {
    console.log(`  Found ${networkCount} deployment(s): ${Object.keys(registry.deployments).join(', ')}`);
  }
}

function main() {
  console.log("📦 Extracting ABIs from contract artifacts and inlining JSON files...\n");
  
  ensureGeneratedDir();

  // Extract ABIs from contract artifacts
  for (const { artifactPath, output, exportName, contractName } of contractAbis) {
    const outputPath = path.resolve(generatedDir, output);
    inlineAbiFromArtifact(artifactPath, outputPath, exportName, contractName);
  }

  // Aggregate and inline deployments from contracts folder
  const deploymentsOutputPath = path.resolve(generatedDir, "DeploymentsRegistry.ts");
  inlineDeploymentsRegistry(deploymentsOutputPath, "DeploymentsRegistry");

  console.log("\n✅ All files inlined successfully!");
}

main();

